### PR TITLE
Pagination Show All, tonies.json Contribution Page, Dark Mode

### PR DESCRIPTION
**Pull request by henryk86**

### CODE REVIEW

**Comment by henryk86** [comment]
So a first draft of a list of possible candidates where audio Ids are missing is now implemented.

Not sure if I got it right. Currently i show all elements from the tonies.json where no audio ID is set (and exclude currently the additional contents like other episodes (modelnumber starting with 2000)

for example currently there are 4 de-De tonies of category audio-book lacking a audio id...  could this be correct or are that to few?

audio-book
10001471 - Lieblings-Klassiker - Pinocchio (Neuauflage 2024)
10001488 - Nasreddin Hodscha - Seine ersten Abenteuer
11000274 - Ohrenbär - Mulles Zaubersteinchen
11000736 - Lieblings-Klassiker - Der Zauberer von Oz und zwei weitere Klassiker

image

**Comment by SciLor** [comment]
https://github.com/toniebox-reverse-engineering/tonies-json/blob/release/stats/stats-noconfidence-stock-by-article.de-de.csv
Here, every entry with confidence 0 (no automated confirmation) is listed in that csv.
Every entry with id-sets = 0 should be visible in your list.

**Comment by henryk86** [comment]
> https://github.com/toniebox-reverse-engineering/tonies-json/blob/release/stats/stats-noconfidence-stock-by-article.de-de.csv Here, every entry with confidence 0 (no automated confirmation) is listed in that csv. Every entry with id-sets = 0 should be visible in your list.
> 
> "tunes" can be filtered out, as those are 2000*

okay. then it looks okay how i filter. i've got 4 audio-books and in the posted csv there are only 4 audio book with id-sets = 0

**Comment by henryk86** [comment]
Added a dark Theme :)

New Switcher:

image

(therefor i needed to updated the antd Icons version, which causes a recreation of the packagejson lock...)

and as most important change:

image

overworked the show all button... use now of custom pagination. hope it works well because it was a little bit tricky to get it right with the filtering and so on

**Pull request merged**
