### PR TITLE
Linked Newbie-Guides, finished last flashing guide for cc3200 

### PR DESCRIPTION
**Pull request by henryk86**

### CODE REVIEW

**Comment by henryk86** [comment]
image
image
image
image
image

**Comment by henryk86** [comment]
image

**Comment by henryk86** [comment]
menu design on mobile devices adapted:

on open Menu:
image
Click on Text leads to page directly, menu is closed,
Click on the expand + of Tonieboxes for example:
image
and then expand the next level:
image

**Comment by Oggymator** [comment]
when it will be released in the master branch?
have the problem that only 115200 work for me with ESP32 Box

**Pull request merged**
