### PR TITLE
Fixed FileBrowser filterbugs

### PR DESCRIPTION
**Pull request by henryk86**

### CODE REVIEW

**Comment by henryk86** [comment]
fixes https://github.com/toniebox-reverse-engineering/teddycloud/issues/224

**Comment by henryk86** [comment]
additionally:

image
https://github.com/toniebox-reverse-engineering/teddycloud_web/issues/144

**Comment by henryk86** [comment]
{12213ED7-2308-4DF8-907B-F0E564BEFD34}
{949B9480-064F-43FE-BA86-9B3BD1A2AB88}
{20154611-0BC4-412E-B630-DBCE156FA4D5}
{F91EF47C-7F72-4730-B812-1E6682B34777}
{EF2EBBED-F392-457F-BFC1-AFD69F218769}
{B80F0323-B051-491D-8E72-18AB609C4EE9}
{C13D69B6-0C5E-4ABA-846D-21C5F446EF0D}
{6EDF3FAB-EB04-4A83-9F4A-75ABEB164818}
image

**Comment by SciLor** [comment]
Looks nice! Just one little thing I saw: The json has line breaks on the search/replace. May it be possible to keep it in one line as in the original files?

**Comment by henryk86** [comment]
That's autoformatted with stringify

**Comment by henryk86** [comment]
reformatted generated patch json...

added content to last step:
{1141F56D-FCB5-4E17-8D1F-CCF56486791A}
{CD63F232-C3F6-475A-9EFD-5BBF2F258901}
{0E7F78E3-8168-4B8D-853C-2C7C7BAD60D8}
{A48694EC-293B-404F-BE2A-4217B25E1F83}

**Comment by henryk86** [comment]
added identify toniebox with mac page
image

**Comment by henryk86** [comment]
image
image
image

**Comment by henryk86** [comment]
Added Open Toniebox guide:

image

**Pull request merged**
